import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import Banner from '../components/banner';
import Card from '../components/card';

import { fetchCoffeeStores } from '../lib/coffee-stores';

import useTrackLocation from '../hooks/use-track-location';

import { useEffect, useState, useContext } from 'react';
import { ACTION_TYPES, StoreContext } from '../store/store-context';

export async function getStaticProps(context){
  const coffeeStores = await fetchCoffeeStores();

  return {
    props: {
      coffeeStores
    }
  }
}

export default function Home(props) {
  const { handleTrackLocation, locationErrorMsg, isFindingLocation } = useTrackLocation();

  // const [coffeeStores, setCoffeeStores] = useState('')
  const [coffeeStoresError, setCoffeeStoresError] = useState(null)

  const { dispatch, state } = useContext(StoreContext)
  const {coffeeStores, latLong} = state;

  // Set a use effect to manage getting stores by Geolocation
  useEffect(() => {
    // Create an async function that will trigger the fetching of coffee stores
    async function setCoffeeStoresByLocation() {
      if (latLong) {
        try {
          // Run fetch coffee stores logic and pass new latLong values
          const response = await fetch(
            `/api/getCoffeeStoresByLocation?latLong=${latLong}&limit=6`
          );
          
          const coffeeStores = await response.json();

          dispatch({
            type: ACTION_TYPES.SET_COFFEE_STORES,
            payload: {
              coffeeStores
            }
          })

          console.log({ coffeeStores });
          //set coffee stores
          setCoffeeStoresError('');
        } catch (error) {
          setCoffeeStoresError(error.message);
          //set error
          console.log("Error", { error });
        }
      }
    }
    
    // Trigger the function
    setCoffeeStoresByLocation();
  }, [latLong])

  const handleOnBannerBtnClick = () => {
    handleTrackLocation();
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner
          buttonText={isFindingLocation ? "Locating..." : "View stores nearby"}
          handleOnClick={handleOnBannerBtnClick}
        />
        {locationErrorMsg && <p>Something went wrong: {locationErrorMsg}</p>}
        {coffeeStoresError && <p>Something went wrong getting sotres</p>}
        <div className={styles.heroImage}>
          <Image src="/static/hero-image.png" width={700} height={400} alt="Hero Image"/>
        </div>
        {coffeeStores.length > 0 && 
            <>
              <h2 className={styles.heading2}>Stores Near Me</h2>
              <div className={styles.cardLayout}>
                {coffeeStores.map(coffeeStore => {
                  return (<Card 
                    key={coffeeStore.id}
                    name={coffeeStore.name}
                    imgUrl={coffeeStore.imgUrl || "https://images.unsplash.com/photo-1504753793650-d4a2b783c15e?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2000&q=80"}
                    href={`/coffee-store/${coffeeStore.id}`}
                    className={styles.card}
                  />)
                })}
              </div>
            </>
          }
        <div className={styles.sectionWrapper}>
          {props.coffeeStores.length > 0 && 
            <>
              <h2 className={styles.heading2}>Toronto Stores</h2>
              <div className={styles.cardLayout}>
                {props.coffeeStores.map(coffeeStore => {
                  return (<Card 
                    key={coffeeStore.id}
                    name={coffeeStore.name}
                    imgUrl={coffeeStore.imgUrl || "https://images.unsplash.com/photo-1504753793650-d4a2b783c15e?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2000&q=80"}
                    href={`/coffee-store/${coffeeStore.id}`}
                    className={styles.card}
                  />)
                })}
              </div>
            </>
          }
        </div>
      </main>

    </div>
  )
}
